<?php
/**
 * TL_ROOT/system/modules/cookiebar/languages/ru/tl_page.php 
 * 
 * Contao extension: cookiebar 1.0.5 
 * Russian translation file 
 * 
 * Copyright : &copy; 2011-2014 Codefog 
 * License   : LGPL 
 * Author    : Codefog (codefog), http://codefog.pl 
 * Translator: Dmitri Kuznetsov (Kuzmich) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['cookiebar_enable']['0'] = "Включить Cookiebar";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_enable']['1'] = "Отображение панели информации о файлах cookie на вашем сайте.";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_message']['0'] = "Информация о cookie";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_message']['1'] = "Введите краткую информацию о cookie.";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_jumpTo']['0'] = "Страница подробностей";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_jumpTo']['1'] = "Вы можете выбрать страницу с дополнительной информацией о cookie.";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_position']['0'] = "Позиция Cookiebar";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_position']['1'] = "Вы можете выбрать позицию Cookiebar.";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_position']['top'] = "Вверху страницы";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_position']['bottom'] = "Внизу страницы";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_button']['0'] = "Метка кнопки";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_button']['1'] = "Введите метку кнопки (напр., <em>Принять</em>).";
$GLOBALS['TL_LANG']['tl_page']['cookiebar_legend'] = "Информация о cookie";
 
?>
